### ISSUE TITLE
Best fitting hit incorrect

### ISSUE THREAD

**Issue by naurasd** [lokalmatador123/BOLDigger#10]
Hi,

I used classificaiton for COI and then ran the program to find the best fitting hit both with the JAMP and the BOLDigger method. I found a case where both BOLDigger and the JAMP method choose a hit even though another publicly available hit with better taxonomic classification and similarity was found.

Please check the entry for ASV308 in the attached file. BOLDigger and JAMP choose a published hit with a classification to class level and a similarity of 95.12. However, in the sheet showing the 20 best hits, there are several published hits with higher similarity and better classification. The top hit has a similarity of >97% and classification down to species level (although given the similarity value, only genus level callsification should be trusted, obviously).

[BOLDResults_COI_cluster_reps_curated_no_contam.xlsx](https://github.com/DominikBuchner/BOLDigger/files/8748981/BOLDResults_COI_cluster_reps_curated_no_contam.xlsx)

A bug?

Cheers

Nauras

**Comment by DominikBuchner** [comment]
I'm on it.

best Dominik

**Comment by DominikBuchner** [comment]
Dear Nauras,

I updated the search algorithm for the best hit to account for cases like yours. There is an updated paragraph in the readme on the main page below the JAMP sorting method. Please note that currently BOLDigger GUI and BOLDigger command line are not compatible. I will work on fixing the command line version next.

I will close this issue, and open a new one on the command line GitHub page.

best Dominik

**Comment by naurasd** [comment]
Thanks Dominik. I have curated some of the entries manually now. Looking forward to using the improved algorithm in the future ;-)

Thanks again for this great tool.

**Comment by DominikBuchner** [comment]
Command-line is also updated now including the API correction.
