### ISSUE TITLE
BOLD did not respond! several weeks?

### ISSUE THREAD

**Issue by OndroV** [lokalmatador123/BOLDigger#16]
Dear Dominik and BOLDigger users,

I wonder if you also experience the same cycle of:

```
10:19:50: Requesting BOLD. This will take a while.
10:19:51: Downloading results.
10:19:51: Parsing html.
10:19:51: BOLD did not respond! Retrying.
```
these days. I thought it was due to the BOLD maintenance some days ago, but perhaps not? 

I tried decreasing the batch size to 10 and then to 1, which was finally successful, but after a while it got stuck again.
Now I also noticed that the single sequence in *_done.fasta is incomplete and its last line remained in the original fasta file (attached). Maybe here we have a new format error to include in the checks?
The fasta file passed the BOLDigger check and when I copied the sequences directly into ID engine on BOLD website, I got results normally. 

Thanks,
Ondrej

P.S.:
With this issue I realized how wonderful it would be if BOLDigger did not crash every time I close its process window or when the pc goes to sleep unintentionally. This way I have to enter the folder, file and account info again and again (for some reason Ctrl+C works only once there or not even once in case I click elsewhere before pasting :D )
[boldigger_issue.zip](https://github.com/DominikBuchner/BOLDigger/files/9380468/boldigger_issue.zip)

**Comment by OndroV** [comment]
Replacing the ^M newline character and unwrapping the sequences into 1 line seems to help.  (My issue.fasta comes from Swarm running on Windows)
`cat original.fasta |  tr -d $'\r' | perl -pe '$. > 1 and /^>/ ? print "\n" : chomp' > unwrapped.fasta`
`echo "" >> unwrapped.fasta`

But batch size 50 and 10 didnt work anyway. Is there a new limit from BOLD? Batch size 5 works fine so far...

**Comment by DominikBuchner** [comment]
I have an idea where this comes from, will check in the next few days and come back to you asap.

€: I assume this is COI?!

**Comment by Canxis** [comment]
I have met the same problem, batch size 50 didn't work for COI sequences...

**Comment by Canxis** [comment]
Providing a solution:
I decreased the batch size to 5 when I experience the same error cycle. But the last sequence remained in my original fasta file, error message: IndexError: list index out of range. I emptied the original file, run BOLDigger again and got the excel file. Run the remaining sequence alone to get complete excel file.

**Comment by DominikBuchner** [comment]
There is no real solution to this program (codewise). The problem ist: Some of the entries in BOLD produce a database error on the BOLD website. There is no way to catch this exception since no specific error code is send from the server. It happens rarely but when I encounter it I 1. let BOLD know about the faulty record. 2. change the batch size to 1 to find the faulty record.

**Comment by Canxis** [comment]
Thank Dominik for your quick reply :D )
batch size 5 works fine now

**Comment by OndroV** [comment]
@Canxis maybe the last sequence problem is due to formatting? When I had the same problem, it was solved by appending a new line to the fasta file 
`echo "" >> my.fasta`

@DominikBuchner Yes, it was COI. Thanks for looking into this. 

So I solved the ^M newline issue (it would be nice to cover this in the function Check fasta), and the batch size issue seems to be at BOLD...
