### ISSUE TITLE
Hymenoptera issue

### ISSUE THREAD

**Issue by pollingmarcel** [lokalmatador123/BOLDigger#19]
Hey Dominic,

First: BOLDIGGER is truly a great tool. We do a lot of insect metabarcoding at the moment and wouldn't get such high quality results without your it, so thank so much for constructing it!

One small issue keeps coming up that I think you should know: Hymenoptera hits don't get transported correctly to the results. Here's an example in the BOLDResults file:
![image](https://user-images.githubusercontent.com/69917434/192251539-d4dd726e-090d-4edd-af19-662955f9c564.png)

And here's the hits on BOLD website:
![image](https://user-images.githubusercontent.com/69917434/192251689-63fa41e3-d712-42b0-b3fb-b996f6db9fcb.png)

I also notice that the order in which the ASVs are in the 'BOLDigger hit' tab of the BOLDResults excel file are skewed whenever a Hymenopteran comes up:
![image](https://user-images.githubusercontent.com/69917434/192252132-b8c2c5fc-6a86-4f8d-80d6-79f247d8a762.png)
 versus the order in the first tab (starting with 'Run dd/mm/yyyy tt.tt'):

>0cc778207a38b7a6e881d96d2ae63bbf
>1a994f0b7d83ca1fd64f85e5463ab493
>20f61de5ad7c87a8320d5a7c6c403aae
>28052a092ec236890bf2034336b82950 (this one is different, but also a Hymenopteran)
>4a8e00925b4fcd21335a0ee102ffcba2

I'm not sure what could be causing it, but just wanted to flag it. The primer pair I use (mlCOIintF, HCO2198) is not great at Hymenopterans (or so I understand from literature) but I'm wondering if it could have to do with the bioinformatics..

Thanks for your thoughts in advance, hope I explained it well to you,

Best regards,

Marcel Polling

**Comment by DominikBuchner** [comment]
Hi Marcel, 
thanks for the kind words, I'm happy that the tool is of use for a lot of people :).
This looks like a strange issue, I will take a look at this asap. Can you please also upload the fasta file that I causing the issue(s)? One or a couple of sequences that cause trouble, then I will first try to reproduce the problem and if I can reproduce it consistently try to find the reason and a fix. There shouldn't be anything special about the Hymenoptera string from the computers perspective.

best Dominik

**Comment by pollingmarcel** [comment]
Hey Dominic,

Sorry for the late reply, I've been away from this project for a bit. Now I got back to it and suddenly I couldn't run BOLDIGGER anymore, so I re-installed it but I get very weird output file that I cannot seem to open: BOLDResults_Projectname-dn98.h5.lz. I don't suppose it has anything to do with the warning I get about tkinter (see below)?

UserWarning: You are running a VERY old version of tkinter 8.5.13. You cannot use PNG formatted images for example.  Please upgrade to 8.6.x

Attached is a fasta file with some records that were not ideally classified using BOLDIGGER LCA script, although possibly you've fixed these in the new version :) I've also added some Diptera to the list where I found something different in the BOLDigger output than on the website.

Thanks for your help!

Best regards
[Seqs-BOLDigger.xlsx](https://github.com/DominikBuchner/BOLDigger/files/9745111/Seqs-BOLDigger.xlsx)


Marcel

**Comment by DominikBuchner** [comment]
Hi Marcel,
the results will be converted once the complete fasta file is blasted. I use the hdf file as a temporary savefile, because it has constant read/write speeds and therefore speeds up the saving of the downloaded results a lot. Please a) upload the fasta that is causing the issue so I can run the query myself or b) run the assignment and send me the .xlsx file that is generated at the end.

**Comment by pollingmarcel** [comment]
[Sequences_BOLDigger.txt](https://github.com/DominikBuchner/BOLDigger/files/9745898/Sequences_BOLDigger.txt)

Here's the file in txt format (fasta not supported by github)

**Comment by DominikBuchner** [comment]
Hi, 
for me the websites output and BOLDigger output match perfectly. See the attached results. 

[BOLDResults_Sequences_BOLDigger_part_1.xlsx](https://github.com/DominikBuchner/BOLDigger/files/9746274/BOLDResults_Sequences_BOLDigger_part_1.xlsx)

Was there maybe an extended period of time between your initial search and the website search? The database could have changes in between.

**Comment by pollingmarcel** [comment]
Hi Dominic,

You are completely right. A simple BOLDigger update fixed the problems right away.. so sorry to have bothered you with this, thanks a lot for your help though!

Best regards

Marcel

**Comment by DominikBuchner** [comment]
nothing to apologize for. happy to help :)
