### ISSUE TITLE
need to check end of fasta file

### ISSUE THREAD

**Issue by OndroV** [lokalmatador123/BOLDigger#2]
Hello, first of all, big thanks and thumbs up for this wonderful tool!

If my fasta file comes directly from JAMP's <0.01% read abundance filtering (as attached error_1.fasta), I need to remove the last 2 lines:
```
>below_0.01
 NA
```
otherwise boldigger crashes and terminal shows an error `UnboundLocalError: local variable 'index' referenced before assignment`
I also had to make sure an empty line is after the last sequence. Because if number of OTUs (in the last batch) is equal to batch size and there's no empty line after the last OTU sequence, I get the error as well.
While playing around with the issue, it also sometimes crashed with `IndexError: list index out of range` and the same traceback (see below). Seems like this happens when the empty line is the only thing in the last batch, which is no problem, because all OTUs are already processed at that point.

I am new to python and now I have no time to suggest a fix. So in case you decide that it's not worth fixing in the code, it would be useful at least to tell users through README that they might need to edit their fastas as I did. Good luck!

`Traceback (most recent call last):
  File "/home/ono/.local/bin/boldigger", line 11, in <module>
    sys.exit(main())
  File "/home/ono/.local/lib/python3.6/site-packages/boldigger/__main__.py", line 60, in main
    boldblast_coi.main(session, values['fasta_path'], values['output_folder'], values['batch_size'])
  File "/home/ono/.local/lib/python3.6/site-packages/boldigger/boldblast_coi.py", line 246, in main
    dataframes = save_as_df(html_list, sequences_names[querys.index(query)])
  File "/home/ono/.local/lib/python3.6/site-packages/boldigger/boldblast_coi.py", line 104, in save_as_df
    cols = dataframes[index].columns.tolist()
UnboundLocalError: local variable 'index' referenced before assignment`

**Comment by OndroV** [comment]
Hmm, now that I returned to the issue after some hours, everything is working fine even without the empty line. Maybe it was just a connection issue? If yes, then I appologise for the disturbance and my only message to other users is "Remove the lines: >below_0.01" and "NA"  :-) 

Still, I'd be grateful if someone checked my sanity and tried the attached COI sequences in the following 4 scenarios. Please let me know in which scenario you get an error. 
1)  error_at_bs47.fasta with batch size = 47
2)  error_at_bs47.fasta with batch size = 100
3)  47otus+emptyline.fasta with batch size = 47
4)  47otus+emptyline.fasta with batch size = 100
Thanks!

*I am pretty sure that 1) and 3) were consistently giving errors in the morning. 2) and 4) were consistently working fine. Now only 3) is giving the IndexError, which is no problem... Strange things happen.
[error_at_bs47.zip](https://github.com/DominikBuchner/BOLDigger/files/4638149/error_at_bs47.zip)
[47otus+emptyline.zip](https://github.com/DominikBuchner/BOLDigger/files/4638150/47otus%2Bemptyline.zip)

**Comment by DominikBuchner** [comment]
The problem is that posting a request that contains ">below_0.01\nNA" won't get a parsable answer from the bold identification engine, since it is not a valid sequence. 

Still will find a way to fix this, maybe check the fasta file before the request is sent! Thanks for point that out, I'll work on it.

€: Tested all files. All are working fine except 3). So what boldigger does is cut your fasta file to batch sizes, depending on the input number. Since in the .fasta file there are 95 lines with the last line just being empty it will create a second batch containing nothing. The solution is to fix your .fasta file, the code is fine. I will add a line to the readme.
