### ISSUE TITLE
trouble running jamp_hit and digger_hit

### ISSUE THREAD

**Issue by filipamsmartins** [lokalmatador123/BOLDigger#20]
Hello @DominikBuchner ,

I am struggling with getting jamp and boldigger methods to run, both in command line and interface. This is the first dataset I am running since I have updated to the new version, and it keeps failing when creating a new sheet:

13:27:20: Opening resultfile.
13:27:47: Filtering data for JAMP hits.
13:30:35: Extracting additional data.
13:31:41: Flagging the hits.
13:34:59: Saving result to new tab.
Traceback (most recent call last):
  File "/home/filipamsmartins/.local/bin/boldigger-cline", line 8, in <module>
    sys.exit(main())
  File "/home/filipamsmartins/.local/lib/python3.8/site-packages/boldigger_cline/__main__.py", line 70, in main
    digger_sort.main(args.xlsx_path)
  File "/home/filipamsmartins/.local/lib/python3.8/site-packages/boldigger_cline/digger_sort.py", line 30, in main
    save_results(xlsx_path, output)
  File "/home/filipamsmartins/.local/lib/python3.8/site-packages/boldigger/digger_sort.py", line 128, in save_results
    writer.book = wb
AttributeError: can't set attribute

Thank you in advance for your help. Best,
Filipa

**Comment by DominikBuchner** [comment]
Hi Filipa,
can you maybe upload the file that causes this issue?
best Dominik

**Comment by filipamsmartins** [comment]
Hi Dominik, please find the file attached. thanks

[BOLDResults_COI_part_1.xlsx](https://github.com/DominikBuchner/BOLDigger/files/9708719/BOLDResults_COI_part_1.xlsx)

**Comment by DominikBuchner** [comment]
I cannot reproduce this problem. 
Can you try to update pandas and openpyxl and see if the problem persists? 

`pip install --upgrade pandas`
`pip install --upgrade openpyxl`

**Comment by filipamsmartins** [comment]
I have tried the commands you provided and get all 'Requirement already satisfied'. And I checked and I have all packages up to date. Eventhough, the problem still persists. what could it be?

**Comment by filipamsmartins** [comment]
Hi Dominik, I found the problem. I am running boldigger in windows through wsl and it has completed now when I opened wsl as root. The strange thing is that with the previous version (1.5), I worked perfectly fine in the normal environment. If you could find a solution to this it would be great, to avoid future conflicts with pip; meanwhile I will go forward using root. best,
Filipa

**Comment by DominikBuchner** [comment]
Hi Filipa,

Can you upload the file that is causing the issue?

Best Dominik

filipamsmartins ***@***.***> schrieb am So., 2. Okt. 2022,
18:25:
