### ISSUE TITLE
Bold not responding

### ISSUE THREAD

**Issue by frannasc** [lokalmatador123/BOLDigger#22]
Hi and thank you for developing this tool
We have tried to our fasta file with BolDigger but unfortunately we get an error message saying that bold is not responding when it tries to download the results

We have run the cline pipeline with your test database and get the same results. Any suggestion s on how to solve this? 
Thi is the code we have tried
boldigger_cline ie_coi username password C:\Users\elbr2874\Downloads\COI.fasta C:\Users\elbr2874\Desktop\boldresults
Best
Francisco

**Comment by DominikBuchner** [comment]
Dear Fransisco,

I'm currently on vacation until the 23rd of January. I can look into this
afterward. What you could do right away:

1. Confirm that the fasts file is in the 2-line fasts format. E.g. one line
per title and sequence.

2. Try blasting your file on the bold website and see if this works.

3. Try again after some time. Sometimes bold does noe respond for some time.

4. Upload the file to GitHub so I can try to replicate the problem.

Best wishes from fuerteventura
Dominik

frannasc ***@***.***> schrieb am Mi., 18. Jan. 2023, 13:44:

**Comment by frannasc** [comment]
Dear Dominik
Thanks for the answer and I hope you've had a nice vacation. I think the problem was related to trying to download the output through the University server, the firewall did not allowed. When we tried from home everything worked well.
Thank you for the help
