### ISSUE TITLE
BOLD Not Responding: Attempting Retry

### ISSUE THREAD

**Issue by onurdogan** [lokalmatador123/BOLDigger#23]
### Description
The messages displayed in the **screenshot** (attached) are repeating every second. I'm uncertain on how long I should wait for the messages to load efficiently. Do you have any insights on this situation?

I am encountering the following log messages:
```
2023-01-29 19:04:06.902 python3.9[50142:2472810] +[CATransaction synchronize] called within transaction
2023-01-29 19:04:26.391 python3.9[50142:2472810] +[CATransaction synchronize] called within transaction
```

Additionally, I've included the script below as an example of my "*.fasta" file. The file contains information, followed by quality score, and actual sequence data shortened as "SEQUENCESEQUENCE", original lenght of DNA seq is like 190 bp.

My original fasta file contains many entries, but for now, I'm testing with just like 10 lines. Can you suggest a specific fasta file to use following a step such as Obitools?

>***:50:HL725AFX3:1:11101:7839:1038 count=1128; obiclean_count={'XXX': 1296}; obiclean_head=True; obiclean_cluster={'XXX': 'NB552469:50:HL725AFX3:1:11101:7839:1038'}; obiclean_internalcount=0; obiclean_status={'XXX': 'h'}; obiclean_samplecount=1; obiclean_headcount=1; obiclean_singletoncount=0;    1:N:0:ATTGTAAT+NAACCGCG
SEQUENCESEQUENCE...

### Screenshots

<img width="349" alt="image" src="https://user-images.githubusercontent.com/11692156/215347902-7b4f636f-e259-41e1-b7e2-0f63a00774b3.png">

<img width="349" alt="image" src="https://user-images.githubusercontent.com/11692156/215344189-1042b606-6519-4187-8b42-33b87af9fca5.png">

### Environment
python3.9

Thanks for your time.
Onur.

**Comment by DominikBuchner** [comment]
Hi Onur,
your fasta file should look like the standard 2-line fasta format, e.g. 

```
>Header_1
SEQUENCESEQUENCESEQUENCE......
>Header_2
SEQUENCESEQUENCESEQUENCE......
```

Can you please upload the fasta file you are trying to blast? I think I remember, that BOLD only allows a certain header length, but would have to run a test with your file. Then we can find a solution, e.g. shortening the headers for example.

best Dominik

**Comment by onurdogan** [comment]
Hi Dominik,

I've shortened the headers as instructed, but the issue remains. 
-The remote run of the test file with blastn db was successful-.

A sample header like:
`>H_17383_1082_4496`

I **[shared link](https://www.dropbox.com/s/pxtq3m0sx022w0s/test2-boldigger.fasta?dl=0)** to a sample of 5 line sequences.

Thanks.

**Comment by DominikBuchner** [comment]
Hi Onur,
as I sad, the fasta needs to be converted to 2line format. I'm still planing to implement this automatically. If you need help with the conversion, just let me know / upload the complete file. Boldigger will run fine after doing so. If you know a bit of python you can just install Biopython and do the conversion with this one-liner:

```
from Bio import SeqIO
SeqIO.convert("input.fasta", "fasta", "output.fasta", "fasta-2line")
```

Uploaded an example of how it should look. 

best Dominik
[2line.txt](https://github.com/DominikBuchner/BOLDigger/files/10534914/2line.txt)

**Comment by onurdogan** [comment]
Dear Dominik,

I wanted to let you know that I have tried the 2line.fasta file you shared and it's working now. Thank you for your time and effort in providing a solution to my issue.

Best regards.

<img width="354" alt="image" src="https://user-images.githubusercontent.com/11692156/215474981-0cfee958-bb74-4de3-94f7-89df702ea5be.png">
