### ISSUE TITLE
error "Unable to complete operation on element with key out"

### ISSUE THREAD

**Issue by Rishikeshklaxmi** [lokalmatador123/BOLDigger#26]
Hey Dominik
I am unable to process my data as it shows an error "Unable to complete operation on element with key out"
Please suggest the possible solution for this.

With regards 
Rishikesh Krishan Laxmi
<img width="1440" alt="Screenshot 2023-08-18 at 1 53 19 PM" src="https://github.com/DominikBuchner/BOLDigger/assets/142579696/cc1b52c0-1bdb-4ac8-b499-8c0eb128fcae">

<img width="1440" alt="Screenshot 2023-08-18 at 1 53 19 PM" src="https://github.com/DominikBuchner/BOLDigger/assets/142579696/9862afed-ceaa-43f6-905f-b9b65798a4ec">

**Comment by DominikBuchner** [comment]
Hi Rishikesh,
never seen this and it will take me some time to fix which I don't have at the moment. The simplest way for you would be to fall back to the command line version: 
https://github.com/DominikBuchner/BOLDigger-commandline

Will fix this as soon as I find the time.

best
Dominik

**Comment by Rishikeshklaxmi** [comment]
Hey Dominik

Thank you so much for your swift response. I am not aware of the command
line version. So, I will try to resolve this otherwise i will use another
computer for the same analysis.

regards
Rishikesh
