### ISSUE TITLE
Private entry as top hit despite 100% similarity published entry available

### ISSUE THREAD

**Issue by naurasd** [lokalmatador123/BOLDigger#28]
Hi,

I am running BOLDigger v2.2.0 on the COI sequences in the txt file attached.

I am performing all the steps:

1. Running the identification engine with a batch size of 5.
2. Searching additional data
3. Adding top hits with BOLDigger method.
4. Download additional identification data via BOLD API for correction.

I encountered a weird behavior for MOTU23. See the top 20 hits for this MOTU:

![grafik](https://github.com/DominikBuchner/BOLDigger/assets/62713295/37d89f78-9546-4363-92ef-f3defc1c1602)

BOLDigger hit sheet:

![grafik](https://github.com/DominikBuchner/BOLDigger/assets/62713295/72f33e02-66c2-4c80-b477-62f7dd9986b7)

BOLDigger hit - API corrected sheet:

![grafik](https://github.com/DominikBuchner/BOLDigger/assets/62713295/a8530b16-66cb-4a3f-a8d8-f2b035e8a0d8)

Why does BOLDigger ends up with a private entry as the chosen hit? Why doesn't it choose a published entry? Why doesn't it choose _Botrylloides leachi(i)_ as the top hit?

Sequences attached for you to reproduce the problem.

Cheers

nauras
[seqs_test.txt](https://github.com/DominikBuchner/BOLDigger/files/12513907/seqs_test.txt)

**Comment by DominikBuchner** [comment]
Hi nauras,

It simply use the first hit from the most common selections. So this is
intended and not a bug.

Best
Dominik

naurasd ***@***.***> schrieb am Mo., 4. Sept. 2023, 14:51:

**Comment by naurasd** [comment]
Ok so in this case I am a bit unlucky, because B. lechi(i) comes with two different spellings and is there less common among the top 20 hits than B. diegensis?

**Comment by DominikBuchner** [comment]
Yes there's know way to tell those to apart programatically...

naurasd ***@***.***> schrieb am Di., 5. Sept. 2023, 08:53:

**Comment by naurasd** [comment]
fair enough ;-)

**Comment by naurasd** [comment]
As an idea: Could there be a way in the future to not give a species level assignment if there is two different species with 100% similarity? would this make sense? Because as in this case here, COI obviously doesn't have enough resolution in this fragment to distinguish between species of this genus.

**Comment by DominikBuchner** [comment]
This is shown by one of the flags implemented :)

naurasd ***@***.***> schrieb am Di., 5. Sept. 2023, 10:00:

**Comment by naurasd** [comment]
ah yes, I somehow remembered that the flag no. 2 means the selected top hit was a private one.
 got it now ;-)

**Comment by OndroV** [comment]
> As an idea: Could there be a way in the future to not give a species level assignment if there is two different species with 100% similarity? would this make sense? Because as in this case here, COI obviously doesn't have enough resolution in this fragment to distinguish between species of this genus.

Thanks for bringing this up @naurasd ! Also we spend a lot of effort manually reviewing the taxonomy. @DominikBuchner when you have time and will to improve this, how about inviting us users for a short online discussion to design some helpful features, please? 
Currently it often requires opening the identification page to get more hits (top 50 or 100) , looking up the BINs, their proportion of species names, authors etc. I guess some of this could be helped by a program
Thanks, Cheers!

**Comment by DominikBuchner** [comment]
Hi,

Whatever I can to I'll try to implement. Will be back from vacation
September 18th.

Ondrej Vargovčík ***@***.***> schrieb am Mi., 6. Sept. 2023,
07:12:
