### ISSUE TITLE
Supspecies information dropped from best fitting hit

### ISSUE THREAD

**Issue by naurasd** [lokalmatador123/BOLDigger#29]
Hi,

any reason why subspecies assignments are dropped when BOLDigger v2.2.0 chooses the best hit?

Cheers

Nauras

**Comment by DominikBuchner** [comment]
As there are almost no subspecies information and it's kind of an
in-between taxonomic rank undecided to drop them.

naurasd ***@***.***> schrieb am Mi., 6. Sept. 2023, 13:22:

**Comment by naurasd** [comment]
got it. i have a few 99-100% similarity hits with subspecies assignment, but i guess it it not crucial to the tool
