### ISSUE TITLE
windows: crash fixed by updating beautifulsoup4

### ISSUE THREAD

**Issue by bwprice** [lokalmatador123/BOLDigger#31]
BOLDigger crashes on windows 10, claiming Pandas needs beautifulsoup4 v 4.11.1 or newer (my machine had 4.10 installed). 

Fixed by forcing an upgrade of bs4 using:
pip install --upgrade beautifulsoup4

**Comment by DominikBuchner** [comment]
Hi Ben,

Thanks for the notice. I'll update the installation soon.

Best
Dominik

Ben Price ***@***.***> schrieb am Mi., 4. Okt. 2023, 22:14:

**Comment by DominikBuchner** [comment]
Fixed with BOLDigger2.
