### ISSUE TITLE
Filter possible NUMTS from BOLDigger assignments

### ISSUE THREAD

**Issue by AlvaroFueyo** [lokalmatador123/BOLDigger#32]
It is possible that in the metabarcoding amplification process not only the mitochondrial gene [but also nuclear copies of that gene were amplified](https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1000834).  And they can lead to false positive detection and identification in the BOLDigger and JAMP pipeline. 

These copies are marked as UNVERIFIED by NCBI in its database (GenBank) if it detects internal codons or INDELs (in the internal sequences of genes where there should not be any).

It could be not so hard to incorporate into BOLDigger the detection of these sequences by adding a new FLAG if internal stopcodons are detected in the sequences after assigning them ([given that the stopcodons depend on the taxonomic group to which each OTU belongs](https://www.ncbi.nlm.nih.gov/Taxonomy/Utils/wprintgc.cgi#SG1)).

Thank you very much for this wonderful pipeline, best regards!

**Comment by AlvaroFueyo** [comment]
Another way to remove nuMT copies. NCBI has sequenced some nuMT, so it may be possible to remove them by removing reads with 100% similarity to them. More on this here: https://link.springer.com/article/10.1186/s12859-021-04180-x

**Comment by DominikBuchner** [comment]
On the TODO list for BOLDigger2.
