### ISSUE TITLE
Assigning BIN to top hits

### ISSUE THREAD

**Issue by gjdury** [lokalmatador123/BOLDigger#33]
Getting Barcode Index Numbers (BINs) could be useful for certain analyses as a extra source of information, especially in datasets with many undescribed species. 

I imagine the procedure for assigning BIN as something along the lines of:
- Initially use the same algorithm as for assigning JAMP hits. 
- If the threshold is set at 98% at step 2, then attempt to assign a BIN. 
- For this, use the same subset of hits as used in step 5 of the JAMP algorithm (“Look for the most common hit that has no missing values”) and check for the number of unique BINs within this subset. 
- If this number is 1, assign that unique BIN. 
- If more than one BIN is found in the subset, do not assign a BIN (i.e., leave the BIN field empty). Perhaps these cases could be flagged (with a number and a list of the unique BINs found).

**Comment by OndroV** [comment]
Thanks for your [pull request](https://github.com/DominikBuchner/BOLDigger/pull/35), @gjdury . I also started using your version of jamp_hit.py with boldigger_cline. For anyone wondering how to "install" it, you can follow this procedure:

Locate your boldigger installation, e.g. from within python in your terminal:
`python`
`import inspect`
`import boldigger`
`print(inspect.getfile(boldigger))`
>  /PATH/TO/YOUR/boldigger/__init__.py

Exit python (e.g. via Ctrl+Z), download the raw [jamp_hit.py](https://github.com/gjdury/BOLDigger/blob/master/boldigger/jamp_hit.py) and move it to your boldigger folder:
`mv /PATH/TO/YOUR/Downloads/jamp_hit.py  /PATH/TO/YOUR/boldigger/`

That's it. Cheers!

**Comment by DominikBuchner** [comment]
At the moment I'm to busy for implementation but as soon as I have time again I'll check if I can integrate it and merge it into BOLDigger directly.

**Comment by OndroV** [comment]
Sure, Thank you! I am also wondering about two things here:

1. Is there any possibility for BOLDigger to switch from Top 20 hits to Top 100 ? (There are BINs with maany records, often private, so the Top 20 hits have poor taxonomy, only the later hits provide good information along with the actual BIN number)

2. Is there a way to automatically browse the obtained BIN websites? I mean to gather information about taxonomy, especially what species names have been assigned to that BIN and how many records support each of the assigned names.
![image](https://github.com/DominikBuchner/BOLDigger/assets/61538402/32b2f95c-1dab-4df6-a230-ece38192a461)

Best,
Ondrej

**Comment by DominikBuchner** [comment]
1. This is currently impossible without severe hacking I think, but I'll check the possibilities in the backend of the BOLD database. 
2. Yes this can certainly be implemented, BINs should have an individual ID so I can probably reconstruct the Link to this Page.

**Comment by DominikBuchner** [comment]
Okay, I just check for the top 100 hits, and have to admit it is embarrassingly easy to get to this data. I'll try to wrap it all up in a big BOLDigger update in April! Then going for top 100 hits will be the new default, makes sense anyways! Then I'll also implement the BIN options as well as information about additional data. Thanks for bringing this up :) @OndroV

**Comment by OndroV** [comment]
:D Perfect! Thank you, looking forward.
(Then I guess also the API correction would be applicable for BINs ... sorry, perhaps this is a silly reminder of an obvious to-do, but I write it down just in case)

**Comment by DominikBuchner** [comment]
Fixed with BOLDigger2.
