### ISSUE TITLE
Passing literal html to 'read_html' is deprecated and will be removed in a future version.

### ISSUE THREAD

**Issue by gjeunen** [lokalmatador123/BOLDigger#34]
Hello @DominikBuchner,

Thank you for creating this awesome tool!

Just to note that I've received the following warning when running BOLDIGGER via the command line (`boldigger-cline ie_coi`). It seems to run fine at this point, but might become an issue in the future?

```
boldigger/boldblast_coi.py:69: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
```

Thanks,
Gert-Jan

**Comment by DominikBuchner** [comment]
Added to my update list, will be easy to fix. Thanks for using boldigger and spitting this :)

**Comment by DominikBuchner** [comment]
Fixed with BOLDigger2.
