### ISSUE TITLE
Limit PySimpleGUI requirement to version 4

### ISSUE THREAD

**Issue by hjarnek** [lokalmatador123/BOLDigger#36]
[PySimpleGUI 5 is out, but is now closed-source and subscription-based](https://news.ycombinator.com/item?id=39369353)

Although the subscription is free for non-commercial users, which includes most of us, it requires you to acquire a free license once a year by ticking a pop-up box. This creates problems in automatic installations of BOLDigger, like when setting up venvs or conda environments, and is especially annoying for people only using BOLDigger-commandline, where the PySimpleGUI requirement is completely superfluous. It also means with PySimpleGUI 5 BOLDigger cannot be called completely open-source anymore...

I would suggest to just limit the range of acceptable PySimpleGUI versions in the requirements spec for BOLDigger.
`"PySimpleGUI >= 4.18.2, < 5.*.*"`

**Comment by DominikBuchner** [comment]
Will do with the next update

Joel Hjärne Kokk ***@***.***> schrieb am Do., 4. Apr. 2024,
12:34:

**Comment by DominikBuchner** [comment]
Fixed with BOLDigger2
