### ISSUE TITLE
Broken login

### ISSUE THREAD

**Issue by voa257** [lokalmatador123/BOLDigger#37]
Hi, Dominik,

Recently, I've encountered an issue where the Boldigger GUI becomes unresponsive when attempting to log in to BOLD. This problem occurs not only on my computer (macOS, python 3.9.18) but also on those of my colleagues (Ubuntu 22.04, python 3.9.18), even on fresh installs of Boldigger.

I am unsure if this issue is related to specific versions of required Python modules or if it is a problem with the BOLD webpage itself. It appears that the POST request to "https://boldsystems.org/index.php/Login" is not functioning as expected.

Best,
Víctor

**Comment by DominikBuchner** [comment]
Hi Victor,

I'm currently working on boldigger2 to fix many of the issue that were
raised here. It will be ready in the next 2 weeks.

Best
Dominik

voa257 ***@***.***> schrieb am Fr., 17. Mai 2024, 11:53:

**Comment by voa257** [comment]
Great news! Glad to hear you're working on Boldigger2 to fix these issues. Also, congrats on the fantastic work with the application.

Best,
Víctor

**Comment by DominikBuchner** [comment]
Fixed with BOLDigger2.
