### ISSUE TITLE
Log in problem

### ISSUE THREAD

**Issue by lukazuvic** [lokalmatador123/BOLDigger#38]
Dear Dominik, 
I have been having a problem with Boldigger since the Bold Systems website was updated, and everything was working perfectly before the update. When I try to log in to my Boldm Systems account in Boldigger, I get this error:
raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='boldsystems.org', port=443): Max retries exceeded with url: /index.php/Login (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1007)'))).
Is there a solution to this problem?

Kind regards,
Luka

**Comment by DominikBuchner** [comment]
Hi Luka, 
I was not aware that the website was updated. Can you try https://github.com/DominikBuchner/BOLDigger2 and tell me if it has the same issue?
best
Dominik

**Comment by DominikBuchner** [comment]
Fixed with v2.2.2. You should consider moving to boldigger2 anyways :)

**Comment by lukazuvic** [comment]
Thank you, Dominik, for fixing the problem, and for the suggestions for boldigger2, I will move to it :)
Best,
Luka
