### ISSUE TITLE
Odd results now from BOLD but not earlier

### ISSUE THREAD

**Issue by Anto007** [lokalmatador123/BOLDigger#39]
Hi @DominikBuchner 

I'm now a frequent user of your wonderful tool but yesterday I noticed that weird results are output from quering BOLD via BOLDigger. Here's my test input file containing 4 sequences
[test_ASVs.fa.txt](https://github.com/user-attachments/files/16844340/test_ASVs.fa.txt)

Now this input file gives me the below taxonomy results using the digger_hit approach on boldigger
![Screenshot from 2024-09-03 09-21-08](https://github.com/user-attachments/assets/bf5d57ac-b86d-4c1d-bff7-cb73c6d1818d)

Just a couple of months back, the same 4 sequences gave me the below results (using the same digger_hit approach on boldigger)

![Old_Screenshot from 2024-09-03 09-49-24](https://github.com/user-attachments/assets/7fddbb3a-9ad6-4d51-bbbc-039e86f72aff)

I tried BOLDigger2 and it gives me better results but there is a weird hit there too (see esp. the "Aves" hit result for ASV_1). Any idea as to why this happening? I noticed on the BOLD website that they have temporarily disabled the option "All Barcode Records on BOLD"; Does this affect the accuracy of the results returned by BOLDigger & BOLDigger2? Any ideas on how not to get a "Aves" hit for these query ASVs? Many thanks in advance for your help

![BOLDigger2_Screenshot from 2024-09-03 09-52-37](https://github.com/user-attachments/assets/e50e9a30-59e3-45a9-85d7-57b68eeed963)

**Comment by DominikBuchner** [comment]
Hi there,
I believe this is due to the all barcode records database being disabled at the moment. I expect this behavior to go away after the upgrade of BOLD on October first. Until then, I#d just trust hits with a species level assignment (with BOLDigger2), as they are downloaded from a different database (not the all records on BOLD database).

best
Dominik

**Comment by Anto007** [comment]
Many thanks for your quick response @DominikBuchner- much appreciated!

**Comment by DominikBuchner** [comment]
Also expect some downtime after October first, I will lock myself up for
one week after the update to fix everything

Jant007 ***@***.***> schrieb am Di., 3. Sept. 2024, 09:29:

**Comment by Anto007** [comment]
Hi @DominikBuchner , I'm just sharing here some testing results from my side: With the upgrade of BOLD, BOLDigger appears to be taking longer to finish. Before the upgrade, it used to take <24 hours to finish classifying 7K ASVs but now for the same ASV set, the run time is being displayed as 221 hours!!! A smaller test dataset of 25 ASVs took 20 minutes to finish now while analysis of the same test dataset on February 1st, 2024 had taken only around 3 minutes to complete. Thank you in advance for your hard work & support.

**Comment by DominikBuchner** [comment]
The upgrade of Bold has not happened yet. It seems like it was postponed to
5th if October. I will roll out an update soon after and everything should
be much quicker again

Jant007 ***@***.***> schrieb am Mo., 30. Sept. 2024, 07:36:

**Comment by Anto007** [comment]
Many thanks again @DominikBuchner for your response-much appreciated! Since the temporary disabling of the full database on BOLD is no longer enforced on their current website, I assumed that they have released the upgraded version. I look forward to using BOLDigger again

**Comment by Anto007** [comment]
Hi @DominikBuchner, sorry to bother you again. I noticed this message on the BOLD portal "_The official launch of the 5th version of BOLD Systems has been scheduled to align with the COP16 conference on Oct 21, 2024. There will be soft launches scheduled in between now and then, without downtime._" In this context, I was wondering if we should expect BOLDigger to work as normal only by the end of this month? BOLDigger2 (but not BOLDigger) btw didn't even permit me to log in this morning despite using the correct credentials. Thanks a ton again for any info.

**Comment by DominikBuchner** [comment]
I'm on vacation until the 20th of October. I expect boldigger2 to work as
expected until the 21st. Then I'll do my best to port it to v5. Boldigger
will then be discontinued as I don't won't to maintain two repositories
with somewhat similar functionality. Unless there is overwhelming demand to
support both in the future.

Jant007 ***@***.***> schrieb am Mi., 9. Okt. 2024, 08:34:

**Comment by DominikBuchner** [comment]
Regarding the login issue: please update to the latest version as this
issue was fixed with the latest update :)

Dominik Buchner ***@***.***> schrieb am Mi., 9. Okt.
2024, 09:38:

**Comment by Anto007** [comment]
Thank you again @DominikBuchner. The updated BOLDigger2 package eliminates the login-related issue. I'm aware that bioinfo package maintenance is a very taxing and somewhat thankless job (in terms of career progression or financial remuneration) but if it is going to be possible, I would like to request you to maintain the BOLDigger package too. I'm pretty sure that many users around the world would also share this view of mine (see for example the last comment in this [thread](https://github.com/DominikBuchner/BOLDigger2/issues/13)) My primary concerns are the growing number of COI ASV sequences (especially considering the output of sequencers such as Novaseq from eDNA seq studies) and the significantly long run time on BOLDigger2. For example, I've now started analyzing 7033 ASVs on the updated BOLDigger2 and the approximate run finish time is being displayed as 60 plus hours while I like to think that BOLDigger (when working normally) would have finished running in less than 24 hrs (currently it just keeps hanging though). Yes, I remember you explaining to me that higher accuracy is attained with the BOLDigger2 run as opposed to BOLDigger but from our biology perspective, the BOLDigger results are already sufficiently decent for us and most importantly, it finishes in a reasonable amount of time for our large datasets (i.e., in good times when there's nothing major happening on the BOLD server end). Sorry for the long rant and happy holidays to you. I once again would like to thank you for all your hard work here.

**Comment by DominikBuchner** [comment]
I see your point here. Let's see what the BOLD update brings us in terms of
time, the problem may be resolved altogether by those improvements :)
otherwise I'll see what I can do in maintaining both packages.

Jant007 ***@***.***> schrieb am Mi., 9. Okt. 2024, 16:51:

**Comment by DominikBuchner** [comment]
Also a quick update here: The update to BOLD v5 will bring a lot of changes which I will change in a future package that I'm working on atm. This will then replace BOLDigger and BOLDigger2 altogether and should be much faster. Stay tuned.

**Comment by DominikBuchner** [comment]
Please see: https://github.com/DominikBuchner/BOLDigger3
