### ISSUE TITLE
Wrong file format while using "JAMP pipeline"

### ISSUE THREAD

**Issue by lukylulu** [lokalmatador123/BOLDigger#4]
When adding top hits with the JAMP method, it said the wrong file format. However, using the first hit method was fine.

**Comment by DominikBuchner** [comment]
Hi,

you mind sharing your resultfile? The active tab in the resultfile has to be the run itself, not the top hits. Otherwise BOLDigger will try to collect data from the top hits and sort them, which is impossible.

**Comment by lukylulu** [comment]
[BOLDResults_NJ_OTU_done.xlsx](https://github.com/DominikBuchner/BOLDigger/files/5754017/BOLDResults_NJ_OTU_done.xlsx)
Could you give a file example for using the JAMP method? Thank you!

**Comment by DominikBuchner** [comment]
A now I see the issue. JAMP and BOLDigger sorting method will only work with COI data but not with other markers.
