### ISSUE TITLE
xlsx output file error? 

### ISSUE THREAD

**Issue by naurasd** [lokalmatador123/BOLDigger#7]
Hi @DominikBuchner 

I am having issues making sense of the xlsx output file. I have a fasta with 99 seqs, ASV_1 to ASV_99. 

However, the first column of the xlsx output file only contains odd numbered ASV IDs and some raw sequences in between. Where are my even numbered ASVs and what do the raw sequences mean? Further, the file only contains ASVs down to ASV_87, don't know what happened to the rest. I checked my input fasta, all 99 ASVs are definitely there and have the regular format >ASV_x followed by the raw sequence on the next line.

My output file is attached.

[BOLDResults_queryFile.fa.1.0.560931114014238.xlsx](https://github.com/DominikBuchner/BOLDigger/files/5835868/BOLDResults_queryFile.fa.1.0.560931114014238.xlsx)

Thanks for having a look at it. I really would like to use your tool, but given the current output this seems a bit difficult ;-)

cheers
Nauras

**Comment by DominikBuchner** [comment]
Dear Nauras,

I will have a look at your issue this evening since I'm in the lab atm. We
will find a solution for sure!

Best Dominik

naurasd <notifications@github.com> schrieb am Di., 19. Jan. 2021, 13:49:

**Comment by naurasd** [comment]
sure, cheers ;-)

**Comment by naurasd** [comment]
Issue solved, my problem was that I had line breaks in my fasta ;-)
