### ISSUE TITLE
Correction of top hits via BOLD API not initiated

### ISSUE THREAD

**Issue by naurasd** [lokalmatador123/BOLDigger#9]
Hi @DominikBuchner 

The correction of the top hits is exactly what I need. There are quite a few cases where the top hit has no species level assignment and higher resolution assignment is masked (or "hidden" as you called it). 

The problem is that the correction is njust not being initiated. I am using the GUI for the BOLD API correction (as it doesn't seem to be implemented yet in the command line version). So I did my identification, I downloaded additional data and got my BOLigger top hits. All good. I checked the fasta again, boldigger says it's fine. But when Is elect my results file and the corresponding fasta at the bottom of the GUI and click run, the small window that always pops up when a boldigger process is being initiated and which shows what's going on pops up for like half a second, and then boldigger shuts down the GUI and and boldigger.exe window disappear.

Any idea what is going on here? I would really like to use it as It's a pain to sort this out manually.

Cheers

nauras

**Comment by DominikBuchner** [comment]
Dear Nauras,

Please provide me with both files and I will take a look at this.

Best Dominik

naurasd ***@***.***> schrieb am Fr., 20. Mai 2022, 20:29:

**Comment by naurasd** [comment]
Thanks for the super quick reply.

[BOLDResults_COI_cluster_reps_curated_no_contam.xlsx](https://github.com/DominikBuchner/BOLDigger/files/8743400/BOLDResults_COI_cluster_reps_curated_no_contam.xlsx)
[COI_cluster_reps_curated_no_contam.txt](https://github.com/DominikBuchner/BOLDigger/files/8743408/COI_cluster_reps_curated_no_contam.txt)

The txt is the fasta file, had to upload is as txt, not permited to nupload .fa files here.

**Comment by naurasd** [comment]
I am already running the latest version of boldigger, just as a note.

**Comment by DominikBuchner** [comment]
Dear Nauras,

I cannot reproduce the problem you encounter, for me, all is working fine. Can you please start BOLDigger via command line instead of double-clicking and show me the error message produced when the crash occurs?

Find attached your file with the corrected hits :).

best Dominik

**Comment by naurasd** [comment]
Hi Dominik,

thanks for the quick replies. I think this was the swiftest issue communication I ever had on Github :-D

I would like to run the step via command line, but on the Github page for the command line version, it doesn't seem to be listed. Plus the help for the command line versio  doesn't work for me, see issue here: [https://github.com/DominikBuchner/BOLDigger-commandline/issues/4](url)

I really appreciate that you ran this for me. Unfortunately, the link to the file you uploaded does not work. It just leads back to this thread. Could you try again please?

Thanks so much

Nauras

**Comment by DominikBuchner** [comment]
I will work on the command line issues asap. Don't have too much spare time at the moment but will find a few hours.

[BOLDResults_COI_cluster_reps_curated_no_contam.xlsx](https://github.com/DominikBuchner/BOLDigger/files/8748798/BOLDResults_COI_cluster_reps_curated_no_contam.xlsx)

**Comment by naurasd** [comment]
Hi Domink,

no worries. Thanks for sending the file again.

Maybe just one little advice for the correction method:

If you check the 7th entry in the API corrected sheet (ASV20), you will notice that it has a similarity of 100 but is classified down to class level only. If you look at the initial classification sheet with 20 entries per ASV/OTU, you will see that there is an entry (_Terpios gelatinosus_) with a similarity of 99.68 and classification down to species level. This is even a published record, not a private one. I think it would be a good idea for the correction method to allow such an entry with a very high similarity to be chosen as top hit, even though similarity is not exactly 100. A similarity of >99 still means that genus level classification can be considered as high confidence classification and this obviously holds much more information than the class level assignment available otherwise.

Just a thought.

Thanks again for developing this great tool and for the swift communication.

You may close the issue if you think the small issue I mentioned above may not be implemented easily in your tool.

best

Nauras

**Comment by DominikBuchner** [comment]
This is actually a bug and not intended behavior. Already found the problem in the code but will have to do a rewrite, so this might take 1 or 2 days. Thanks for pointing it out, this should rarely happen will still fix it.

**Comment by naurasd** [comment]
Just found another case (ASV635) where another 100 % similarity hit was available (and even a published one instead of the chosen private one) that had two more levels of classification. Just wanted to mention it, as in this case similarity was 100 in both the chosen and non-chosen hit. So not sure if it's the same bug.
